作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [1]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
import numpy as np
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
#2.呈上題，將以上數列取出偶數。
a[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
#3.呈1題，將數列取出3的倍數。
a[0:21:3]

array([ 0,  3,  6,  9, 12, 15, 18])

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

#1.請問下列兩種將 Array 轉換成 List 的方式有何不同？

list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；
tolist() 才能達成多層的型態轉換。

In [4]:
#2.請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）
import numpy as np

In [5]:
a = np.random.randint(10, size=6)
print(a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('Lenght: ', len(a))
print('type: ', type(a))

[5 3 3 4 3 9]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
Lenght:  6
type:  <class 'numpy.ndarray'>


In [6]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('Lenght: ', len(b))
print('type: ', type(b))

[[3 5 0 2]
 [3 6 1 2]
 [3 1 9 5]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
Lenght:  3
type:  <class 'numpy.ndarray'>


In [7]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('Lenght: ', len(c))
print('type: ', type(c))

[[[4 0]
  [9 0]
  [3 3]]

 [[6 5]
  [0 2]
  [7 3]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
Lenght:  2
type:  <class 'numpy.ndarray'>


In [8]:
# 3.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
print(a.tolist())
print(list(a))

[5, 3, 3, 4, 3, 9]
[5, 3, 3, 4, 3, 9]


In [9]:
print(b.tolist())
print(list(b))

[[3, 5, 0, 2], [3, 6, 1, 2], [3, 1, 9, 5]]
[array([3, 5, 0, 2]), array([3, 6, 1, 2]), array([3, 1, 9, 5])]


In [10]:
print(c.tolist())
print(list(c))

[[[4, 0], [9, 0], [3, 3]], [[6, 5], [0, 2], [7, 3]]]
[array([[4, 0],
       [9, 0],
       [3, 3]]), array([[6, 5],
       [0, 2],
       [7, 3]])]


In [11]:
def tolist(iterable):
    if iterable != np.ndarray:
        return iterable
    restlist = []
    for array in iterable:
        restlist.append(tolist(array))
    return list(restlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5 3 3 4 3 9]
[[3 5 0 2]
 [3 6 1 2]
 [3 1 9 5]]
[[[4 0]
  [9 0]
  [3 3]]

 [[6 5]
  [0 2]
  [7 3]]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  
