作業目標:<br>
嘗試練習log的函式並應用<br>
作業重點:<br>
學員需要複習log的轉換方式<br>
熟悉運用指數函數以及對數函數

題目:<br>
運用投影片中的分貝公式回答下列問題。<br>
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?<br>
2.30分貝的聲壓會是50分貝的幾倍?


In [1]:
import numpy as np 

In [3]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20
LP = 20*np.log(V1/V0)
LP

138.15510557964274

In [ ]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
V1 = (10 **(LP/20))/V0

# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

In [2]:
import numpy as np

In [3]:
np.zeros((2, 3))
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
np.empty((2, 3))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


```
np.zeros是產生一個全部為0的陣列;
np.empty是產生一個未初始化的陣列 --> 宣告 empty 等同於得到一個幾乎接近 0 的 array
```

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [20]:
a = np.random.rand(2, 3)
print(a)

b=np.array(a, dtype = 'int32')
print(b)

[[0.55937589 0.38046198]
 [0.6743987  0.10948029]
 [0.25920418 0.6150074 ]]
[[0 0]
 [0 0]
 [0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [21]:
m = 20
n = 40

c = np.random.randint(m,n,(2,3))
print(c)

[[25 22 24]
 [31 39 38]]
